trigger:
  branches:
    include:
      - master   # Trigger the pipeline on changes to the master branch

pool:
  vmImage: 'windows-latest'   # You can also use 'ubuntu-latest' if preferred

steps:
# 1. Checkout the repository
- task: Checkout@1
  displayName: 'Checkout repository'
  
# 2. Install .NET SDK (for .NET 6.0, used by Azure Functions)
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '6.x.x'  # Ensures the latest available .NET 6 version is used
    installationPath: $(Agent.ToolsDirectory)/dotnet

# 3. Restore dependencies
- task: DotNetCoreCLI@2
  displayName: 'Restore .NET dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'  # Restores all .NET projects in the solution

# 4. Build the solution
- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration Release --no-restore'  # Builds the solution in Release mode

# 5. Publish the function app to a folder
- task: DotNetCoreCLI@2
  displayName: 'Publish function app'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/publish_output --no-restore'  # Publish output goes to a directory

# 6. Archive the published app (create a zip file for deployment)
- task: ArchiveFiles@2
  displayName: 'Archive function app'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish_output'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

# 7. Deploy to Azure Function App
- task: AzureFunctionApp@2
  displayName: 'Deploy Azure Function App'
  inputs:
    azureSubscription: 'AzureServiceConnection'  # Your Azure service connection name
    appType: 'functionApp'
    appName: 'fnSum'  # Your Azure Function App name
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'  # Zip file to be deployed
